# Generated by Django 5.2 on 2025-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0002_alter_libro_options_alter_usuario_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="descripción",
            field=models.TextField(default="Librito choto que escribiste forro"),
            preserve_default=False,
        ),
    ]
