# Generated by Django 5.2 on 2025-04-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_rename_autor_libro_autores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
