# Generated by Django 5.2 on 2025-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_rename_descripción_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.URLField(blank=True, null=True),
        ),
    ]
