# Generated by Django 5.2 on 2025-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_usuario_managers_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
