# Generated by Django 5.2 on 2025-04-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0008_alter_libro_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="titulo",
            field=models.CharField(max_length=150),
        ),
    ]
