# Generated by Django 5.2 on 2025-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0009_alter_libro_titulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="link_lectura",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="libro",
            name="visibilidad",
            field=models.CharField(default="UNKNOWN", max_length=10),
        ),
    ]
