# Generated by Django 5.2 on 2025-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_remove_libro_leido_libro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
