# Generated by Django 5.2 on 2025-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0012_libro_subtitulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="autores",
            field=models.CharField(max_length=500),
        ),
    ]
