# Generated by Django 5.2.8 on 2025-11-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0015_alter_librodeldia_autores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librodeldia",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
