# Generated by Django 5.2.8 on 2025-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0016_alter_librodeldia_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
