# Generated by Django 4.2.27 on 2026-01-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0017_alter_libro_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="librodeldia",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
